version: 1.0.{build}
image: Visual Studio 2017
environment:
  COVERALLS_REPO_TOKEN:
    secure: LJmt2sYpRSDTf+DSWZ0+vOG+PnFvcYwqIk+CXJGKBo0QR4p+8WotE8gcfPgjmGYp
  PreReleaseSuffix: stable
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  GitUser:
    secure: zAdAOUUof3XGDsdOBRYg7J7wZS44iL4VjI/MVGw+JnU=
  GitOwner:
    secure: n6W5JZ7Q/xfZC7b2k3+ORA==
  GitPassword:
    secure: fHangGPAk14u3V1eP3kg5EdekQoKdOsKC0F/A1mvh9IODHCZ92FGjfWb0U2aQ8bu
build_script:
- ps: .\build.ps1 -Target AppVeyor
test: off
artifacts:
- path: artifacts/packages/*.nupkg
- path: artifacts/coverage/*.xml
- path: artifacts/test-results/*.xml
- path: artifacts/resharper-reports/*.xml
- path: artifacts/resharper-reports/*.html
- path: artifacts/coverage/coverage.dcvr
- path: artifacts/test-results/*.trx
deploy:
- provider: NuGet
  server: https://www.myget.org/F/alhardy/api/v2/package
  api_key:
    secure: gIAiACgNj+JzXyLLTe3rLxZyrAB9RpC8Lw81xEjdOLXqotprqEwGiFWRipEqkpps
  skip_symbols: true